name: Build Binaryen

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # Windows x64
          - os: windows-latest
            arch: x64
            cmake-args: >
              -G Ninja
              -DCMAKE_C_COMPILER=clang
              -DCMAKE_CXX_COMPILER=clang++
              -DCMAKE_C_FLAGS="-target x86_64-windows-gnu -W0 -m64"
              -DCMAKE_CXX_FLAGS="-target x86_64-windows-gnu -W0 -m64"
              -DBUILD_STATIC_LIB=OFF
              -DBUILD_SHARED_LIBS=ON
              -DBUILD_TOOLS=OFF
              -DBUILD_TESTS=OFF
            runtime: win-x64

          # Windows x86
          - os: windows-latest
            arch: x86
            cmake-args: >
              -G Ninja
              -DCMAKE_C_COMPILER=clang
              -DCMAKE_CXX_COMPILER=clang++
              -DCMAKE_C_FLAGS="-target i686-windows-gnu -W0 -m32"
              -DCMAKE_CXX_FLAGS="-target i686-windows-gnu -W0 -m32"
              -DBUILD_STATIC_LIB=OFF
              -DBUILD_SHARED_LIBS=ON
              -DBUILD_TOOLS=OFF
              -DBUILD_TESTS=OFF
            runtime: win-x86

          # Linux x64
          - os: ubuntu-latest
            arch: x64
            cmake-args: >
              -G Ninja
              -DCMAKE_C_COMPILER=clang
              -DCMAKE_CXX_COMPILER=clang++
              -DCMAKE_C_FLAGS="-m64 -w -static-libgcc -static-libstdc++"
              -DCMAKE_CXX_FLAGS="-m64 -w -static-libgcc -static-libstdc++"
              -DBUILD_SHARED_LIBS=ON
              -DBUILD_TOOLS=OFF
              -DBUILD_TESTS=OFF
            runtime: linux-x64

          # Linux x86
          - os: ubuntu-latest
            arch: x86
            cmake-args: >
              -G Ninja
              -DCMAKE_C_COMPILER=clang
              -DCMAKE_CXX_COMPILER=clang++
              -DCMAKE_C_FLAGS="-m32 -w -static-libgcc -static-libstdc++"
              -DCMAKE_CXX_FLAGS="-m32 -w -static-libgcc -static-libstdc++"
              -DBUILD_SHARED_LIBS=ON
              -DBUILD_TOOLS=OFF
              -DBUILD_TESTS=OFF
            runtime: linux-x86

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install dependencies
      - name: Install build deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang clang-tools cmake ninja-build gcc-multilib g++-multilib

      - name: Install build deps (Windows)
        if: runner.os == 'Windows'
        run: choco install llvm ninja cmake mingw --no-progress --yes

      # Limit Binaryen to 1 core to prevent thread hang on MinGW
      - name: Limit Binaryen to 1 core
        if: runner.os == 'Windows'
        run: echo "BINARYEN_CORES=1" >> $GITHUB_ENV

      # Configure
      - name: Configure
        run: cmake -S binaryen -B binaryen/build ${{ matrix.cmake-args }}
        
      # Build
      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: cmake --build binaryen/build -- -j$(nproc)
      
      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: cmake --build binaryen/build
        shell: pwsh

      # Copy artifacts
      - name: Copy to NuGet runtime folder
        run: |
          mkdir -p package/runtimes/${{ matrix.runtime }}/native
          cp -r binaryen/build/lib/* package/runtimes/${{ matrix.runtime }}/native/
        shell: bash

      # Upload artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: runtimes-${{ matrix.runtime }}
          path: package/runtimes/${{ matrix.runtime }}
