name: Build Binaryen

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # Linux 64-bit
          - os: ubuntu-latest
            arch: x64
            target: linux
            cmake-args: >
              -DCMAKE_C_FLAGS="-m64 -w -static-libgcc -static-libstdc++"
              -DCMAKE_CXX_FLAGS="-m64 -w -static-libgcc -static-libstdc++"
              -DBUILD_SHARED_LIBS=ON
              -DBUILD_TOOLS=OFF
              -DBUILD_TESTS=OFF
              -DBINARYEN_CORES=1
            runtime: linux-x64
          # Linux 32-bit
          - os: ubuntu-latest
            arch: x86
            target: linux
            cmake-args: >
              -DCMAKE_C_FLAGS="-m32 -w -static-libgcc -static-libstdc++"
              -DCMAKE_CXX_FLAGS="-m32 -w -static-libgcc -static-libstdc++"
              -DBUILD_SHARED_LIBS=ON
              -DBUILD_TOOLS=OFF
              -DBUILD_TESTS=OFF
              -DBINARYEN_CORES=1
            runtime: linux-x86
          # Windows 64-bit
          - os: windows-latest
            arch: x64
            target: windows
            cmake-args: >
              -DCMAKE_C_FLAGS="-m64 -w -static-libgcc -static-libstdc++"
              -DCMAKE_CXX_FLAGS="-m64 -w -static-libgcc -static-libstdc++"
              -DBUILD_SHARED_LIBS=ON
              -DBUILD_TOOLS=OFF
              -DBUILD_TESTS=OFF
              -DBINARYEN_CORES=1
            runtime: win-x64
          # Windows 32-bit
          - os: windows-latest
            arch: x86
            target: windows
            cmake-args: >
              -DCMAKE_C_FLAGS="-m32 -w -static-libgcc -static-libstdc++"
              -DCMAKE_CXX_FLAGS="-m32 -w -static-libgcc -static-libstdc++"
              -DBUILD_SHARED_LIBS=ON
              -DBUILD_TOOLS=OFF
              -DBUILD_TESTS=OFF
              -DBINARYEN_CORES=1
            runtime: win-x86

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-multilib gcc-multilib cmake make

      - name: Install build dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install mingw --version 13.2.0 -y --force

      - name: Configure
        run: cmake -S binaryen -B binaryen ${{ matrix.cmake-args }}

      - name: Build (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: cmake --build binaryen -- -j$(nproc)

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake --build binaryen --config Release
        shell: cmd

      - name: Copy to NuGet runtime folder
        run: |
          mkdir -p package/runtimes/${{ matrix.runtime }}/native
          if [[ "${{ matrix.target }}" == "windows" ]]; then
            cp -r binaryen/bin/* package/runtimes/${{ matrix.runtime }}/native/
          else
            cp -r binaryen/lib/* package/runtimes/${{ matrix.runtime }}/native/
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: runtimes-${{ matrix.runtime }}
          path: package/runtimes/${{ matrix.runtime }}
