name: Build Binaryen

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: x64
            cmake-args: -A x64 -T ClangCL -DCMAKE_CXX_FLAGS="/W0 /MT" -DBUILD_STATIC_LIB=OFF -DBUILD_SHARED_LIBS=ON -DBUILD_TOOLS=OFF -DBUILD_TESTS=OFF
            runtime: win-x64
          - os: windows-latest
            arch: x86
            cmake-args: -A Win32 -T ClangCL -DCMAKE_CXX_FLAGS="/W0 /MT" -DBUILD_STATIC_LIB=OFF -DBUILD_SHARED_LIBS=ON -DBUILD_TOOLS=OFF -DBUILD_TESTS=OFF
            runtime: win-x86
          - os: ubuntu-latest
            arch: x64
            cmake-args: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-m64 -w -static-libgcc -static-libstdc++" -DCMAKE_CXX_FLAGS="-m64 -w -static-libgcc -static-libstdc++" -DBUILD_SHARED_LIBS=ON -DBUILD_TOOLS=OFF -DBUILD_TESTS=OFF
            runtime: linux-x64
          - os: ubuntu-latest
            arch: x86
            cmake-args: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-m32 -w -static-libgcc -static-libstdc++" -DCMAKE_CXX_FLAGS="-m32 -w -static-libgcc -static-libstdc++" -DBUILD_SHARED_LIBS=ON -DBUILD_TOOLS=OFF -DBUILD_TESTS=OFF
            runtime: linux-x86

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang clang-tools cmake make gcc-multilib g++-multilib

      - name: Configure
        run: cmake -S binaryen -B binaryen/build ${{ matrix.cmake-args }}

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: cmake --build binaryen/build -- -j$(nproc)
      
      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: cmake --build binaryen/build --config Release -- /m
        shell: pwsh

      - name: Copy to NuGet runtime folder
        run: |
          mkdir -p package/runtimes/${{ matrix.runtime }}/native
          cp -r binaryen/build/lib/* package/runtimes/${{ matrix.runtime }}/native/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: runtimes-${{ matrix.runtime }}
          path: package/runtimes/${{ matrix.runtime }}
